spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 1000
        heart-beat-timeout: 3000
        ephemeral: false
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8888
    gateway:
      routes:
        - id: borrow-service
          uri: lb://borrowservice
          predicates:
            - Path=/borrow/**
        - id: auth-service
          uri: lb://authservice
          predicates:
            - Path=/auth/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000